CountryWiki.Web/Models/UpdateCountry.cs
namespace CountryWiki.Web.Models;

public class UpdateCountry
{
    public int Id { get; set; }

    [Required, StringLength(200, MinimumLength = 10)]
    public string Description { get; set; }
}

CountryWiki.Web/Pages/Edit.cshtml.cs
namespace CountryWiki.Web.Pages;

public class EditModel : PageModel
{
    private readonly ICountryServices _countryServices;

    public string CountryName {  get; set; }

    [BindProperty]
    public UpdateCountry CountryToUpdate { get; set; }

    public EditModel(ICountryServices countryServices)
    {
        _countryServices = countryServices;
    }

    public async Task OnGetAsync(int id)
    {
        await RetrieveCountry(id);
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            await RetrieveCountry(CountryToUpdate.Id);

            return Page();
        }

        await _countryServices.UpdateAsync(new UpdateCountryModel { 
            Id = CountryToUpdate.Id,
            Description = CountryToUpdate.Description
        });

        return RedirectToPage("./Index");
    }

    private async Task RetrieveCountry(int id)
    {
        var country = await _countryServices.GetAsync(id);
        CountryName = country.Name;
        CountryToUpdate = new UpdateCountry
        {
            Id = country.Id,
            Description = country.Description
        };
    }
}

CountryWiki.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CountryWiki.Web.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

CountryWiki.Web/Pages/Index.cshtml.cs
namespace CountryWiki.Web.Pages;

public class IndexModel : PageModel
{
    private readonly ICountryServices _countryServices;
    private readonly ICountryFileUploadValidatorService _countryFileUploadValidatorService;
    private readonly ISyncCountriesChannel _syncCountriesChannel;

    public GlobalOptions GlobalOptions;
    public IEnumerable<CountryModel> Countries { get; set; } = new List<CountryModel>();
    public string UploadErrorMessage { get; set; } = string.Empty;

    [BindProperty]
    public IFormFile Upload { get; set; }


    public IndexModel(ICountryServices countryServices, 
                      ICountryFileUploadValidatorService countryFileUploadValidatorService,
                      ISyncCountriesChannel syncCountriesChannel,
                      GlobalOptions globalOptions)
    {
        _countryServices = countryServices;
        _countryFileUploadValidatorService = countryFileUploadValidatorService;
        _syncCountriesChannel = syncCountriesChannel;
        GlobalOptions = globalOptions;
    }

    public async Task OnGetAsync()
    {
        Countries = await _countryServices.GetAllAsync();
    }

    public async Task<IActionResult> OnPostUploadAsync(CancellationToken cancellationToken)
    {
        if (Upload == null)
        {
            return await HandleFileValidation("File is missing");
        }

        var uploadedFile = new CountryUploadedFileModel
        {
            FileName = Upload.FileName,
            ContentType = Upload.ContentType
        };

        if (!_countryFileUploadValidatorService.ValidateFile(uploadedFile))
        {
            return await HandleFileValidation("Only JSON files are allowed");
        }

        var parsedCountries = await _countryFileUploadValidatorService.ParseFile(Upload.OpenReadStream());

        if (parsedCountries == null || !parsedCountries.Any())
        {
            return await HandleFileValidation("Cannot parse the file or the file is empty");
        }

        await _syncCountriesChannel.SyncAsync(parsedCountries, cancellationToken);

        return RedirectToPage("./Index");
    }

    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {
        await _countryServices.DeleteAsync(id);
        return RedirectToPage("./Index");
    }

    private async Task<PageResult> HandleFileValidation(string errorMessage)
    {
        UploadErrorMessage = errorMessage;
        Countries = await _countryServices.GetAllAsync();
        return Page();
    }
}

CountryWiki.Web/Pages/Edit.cshtml
@page
@model EditModel
@{
}

<h1>Edit Country - @Model.CountryName</h1>

<form method="post">
    <div asp-validation-summary="ModelOnly"></div>
    <input asp-for="CountryToUpdate.Id" type="hidden" value="@Model.CountryToUpdate.Id" />
    <div>
        <label asp-for="CountryToUpdate.Description"></label>
        <div>
            <textarea rows="4" cols="50" name="@Html.NameFor(m => m.CountryToUpdate.Description)">@Model.CountryToUpdate.Description</textarea>
        </div>
        <div><span asp-validation-for="CountryToUpdate.Description" class="text-danger"></span></div>
    </div>

    <div>
        <input type="submit" value="Save"/>
    </div>
</form>

CountryWiki.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Country Wiki main page";
}

<div class="text-center">
    <h1 class="display-5">Country Wiki main page</h1>
</div>

<form method="post" enctype="multipart/form-data">

<div class="container mb-5 mt-5">
    <div>
    Upload countries (JSON only): 
        <input type="file" asp-for="Upload" />
    </div>
    <div><input type="submit" value="Upload" asp-page-handler="upload"/></div>
    <div class="text-danger">@Model.UploadErrorMessage</div>

@if (Model.GlobalOptions.ProcessingUpload) {
        <div class="text-center text-danger"><h2>A file upload is in progress...</h2></div>
}
</div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Capital City</th>
                <th>Anthem</th>
                <th>Spoken languages</th>
                <th>Flag</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var country in Model.Countries)
            {
                <tr>
                    <td>@country.Id  </td>
                    <td>@country.Name</td>
                    <td>@country.Description</td>
                    <td>@country.CapitalCity</td>
                    <td>@country.Anthem</td>
                    <td>@string.Join(", ", country.Languages)</td>
                    <td><img src="@country.FlagUri" alt="@country.Name" height="25" width="45" /></td>
                    <td><a asp-page="./Edit" asp-route-id="@country.Id">Edit</a></td>
                    <td><input type="submit" asp-page-handler="delete" asp-route-id="@country.Id" value="Delete" /></td>
                </tr>
            }
        </tbody>
    </table>
</form>

CountryWiki.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Country Wiki</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Country wiki main page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>